version: 2
before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...
builds:
  - id: default
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
    main: ./cmd/apkingo
  - id: windows
    env:
      - CGO_ENABLED=0
    goos:
      - windows
    main: ./cmd/apkingo

archives:
  - id: nix
    builds:
      - default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
  - id: windows
    builds:
      - windows
    format: zip
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

brews:
  - name: apkingo
    repository:
      owner: andpalmier
      name: homebrew-tap
    homepage: "https://github.com/andpalmier/apkingo"
    description: "Tool to extract info from APK files"
    license: "Apache-2.0"
    directory: Formula
    test: |
      system "#{bin}/apkingo --help"

checksum:
  name_template: 'checksums.txt'
snapshot:
  version_template: "{{ incpatch .Version }}-next"
changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

dockers:
  - image_templates:
      - "ghcr.io/andpalmier/apkingo:{{ .Tag }}"
      - "ghcr.io/andpalmier/apkingo:latest"
    dockerfile: Dockerfile.release
    build_flag_templates:
      - "--platform=linux/amd64"
    goos: linux
    goarch: amd64