FROM alpine:latest

# Install CA certificates for HTTPS requests (VT/Koodous)
RUN apk --no-cache add ca-certificates

WORKDIR /mnt/
# Copy the binary built by GoReleaser
ARG TARGETPLATFORM
COPY $TARGETPLATFORM/apkingo /usr/local/bin/apkingo

# Set entrypoint
ENTRYPOINT ["apkingo"]
